#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <algorithm>
#include <unordered_map>
#include <iomanip>

#include "../include/BM25.hpp"
#include "../third_party/hnswlib/hnswlib/hnswlib.h"
#include "../include/json.hpp" 

using json = nlohmann::json;

struct DocStats {
    int doc_id;
    std::string text;
    float bm25_score = 0.0f;
    int bm25_rank = 0;
    float hnsw_dist = 0.0f;
    int hnsw_rank = 0;
    float rrf_score = 0.0f;
};

int main() {
    // 1. READ QUERY & QUERY VECTOR
    std::ifstream q_file("data/query.json");
    if (!q_file.is_open()) {
        std::cout << "{\"error\": \"Could not open data/query.json.\"}\n";
        return 1;
    }
    json query_json;
    q_file >> query_json;
    std::string text_query = query_json["text"];
    std::vector<float> dense_query = query_json["vector"];
    
    // Dynamically set HNSW dimensions based on the ML model's output (384 for MiniLM)
    int dim = dense_query.size(); 

    // 2. READ CORPUS & DOCUMENT VECTORS
    std::ifstream c_file("data/corpus.json");
    if (!c_file.is_open()) {
        std::cout << "{\"error\": \"Could not open data/corpus.json.\"}\n";
        return 1;
    }
    json corpus_json;
    c_file >> corpus_json;
    
    std::vector<std::string> corpus;
    std::vector<std::vector<float>> embeddings;
    
    for (const auto& item : corpus_json) {
        corpus.push_back(item["text"]);
        embeddings.push_back(item["vector"].get<std::vector<float>>());
    }

    if (corpus.empty()) {
        std::cout << "{\"error\": \"Corpus is empty.\"}\n";
        return 1;
    }

    // 3. INITIALIZE INDEXES
    BM25 bm25_index(corpus);
    
    hnswlib::L2Space space(dim);
    hnswlib::HierarchicalNSW<float>* alg_hnsw = new hnswlib::HierarchicalNSW<float>(&space, corpus.size(), 16, 200);

    for (size_t i = 0; i < corpus.size(); i++) {
        // passing the vector generated by Python into C++ memory
        alg_hnsw->addPoint(embeddings[i].data(), i); 
    }

    std::unordered_map<int, DocStats> master_stats;
    for (int i = 0; i < corpus.size(); i++) {
        master_stats[i].doc_id = i;
        master_stats[i].text = corpus[i];
    }

    // 4. BM25 KEYWORD SEARCH
    std::vector<float> raw_bm25 = bm25_index.score(text_query); 
    std::vector<std::pair<float, int>> bm25_ranked;
    for (int i = 0; i < raw_bm25.size(); i++) {
        bm25_ranked.push_back({raw_bm25[i], i});
        master_stats[i].bm25_score = raw_bm25[i];
    }
    std::sort(bm25_ranked.rbegin(), bm25_ranked.rend()); 
    for (size_t rank = 0; rank < bm25_ranked.size(); ++rank) {
        master_stats[bm25_ranked[rank].second].bm25_rank = rank + 1;
    }

    // 5. TRUE HNSW SEMANTIC SEARCH
    auto hnsw_result = alg_hnsw->searchKnn(dense_query.data(), corpus.size());
    std::vector<std::pair<float, int>> hnsw_ranked;
    
    while (!hnsw_result.empty()) {
        auto pair = hnsw_result.top(); 
        hnsw_ranked.push_back({pair.first, pair.second}); 
        hnsw_result.pop();
    }
    std::reverse(hnsw_ranked.begin(), hnsw_ranked.end());

    for (size_t rank = 0; rank < hnsw_ranked.size(); ++rank) {
        int doc_id = hnsw_ranked[rank].second;
        master_stats[doc_id].hnsw_dist = hnsw_ranked[rank].first;
        master_stats[doc_id].hnsw_rank = rank + 1;
    }

    // 6. RRF FUSION
    int k = 60;
    std::vector<std::pair<float, int>> final_fused;
    for (auto& pair : master_stats) {
        DocStats& stats = pair.second;
        stats.rrf_score = (1.0f / (k + stats.bm25_rank)) + (1.0f / (k + stats.hnsw_rank));
        final_fused.push_back({stats.rrf_score, stats.doc_id});
    }
    std::sort(final_fused.rbegin(), final_fused.rend());

    // 7. OUTPUT X-RAY JSON
    json output_array = json::array();
    int top_n = std::min(5, (int)final_fused.size());
    for (int i = 0; i < top_n; i++) {
        int doc_id = final_fused[i].second;
        DocStats stats = master_stats[doc_id];
        
        json doc_json = {
            {"final_rank", i + 1},
            {"doc_id", stats.doc_id},
            {"rrf_score", stats.rrf_score},
            {"bm25_rank", stats.bm25_rank},
            {"bm25_score", stats.bm25_score},
            {"hnsw_rank", stats.hnsw_rank},
            {"hnsw_dist", stats.hnsw_dist},
            {"text", stats.text}
        };
        output_array.push_back(doc_json);
    }

    std::cout << output_array.dump(4) << std::endl;

    delete alg_hnsw;
    return 0;
}